import ThemeToggle from "./components/global/ThemeToggle";
import ThemeContextProvider from "./context/ThemeContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <ThemeToggle />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
